; PlatformIO 项目配置 - ESP-IDF framework
; 校园宿舍智能安防门

[env:esp32dev]
platform = espressif32@~6.8
board = esp32dev
framework = espidf

; 串口监视器波特率
monitor_speed = 115200

; 烧录配置
upload_port = COM4
upload_speed = 115200




; 分区表
board_build.partitions = partitions.csv

; 使用自定义 sdkconfig
board_build.sdkconfig = sdkconfig
